language: node_js
sudo: required
services:
 - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install --assume-yes apache2-utils
  - npm install -g npm@2.13.5
  - npm install -g grunt-cli
  - npm config set strict-ssl false
install: npm install
matrix:
  # The acceptance tests only work with node 4 or higher.
  include:
  - node_js: "0.10"
    script: npm test
  # Include sync acceptance tests for node 4
  - node_js: "4.4.3"
    script:
      - npm test
      - npm link
      - git clone https://github.com/feedhenry/sync-acceptance-testing.git
      - cd sync-acceptance-testing
      - npm install
      - npm link fh-mbaas-api
      - npm test
script:
  - npm run test
